---
prometheus:
  host: 0.0.0.0
  port: 9770
  outfile: "/tmp/spu_prometheus_metrics"
ssh:
  host: "localhost"
  user: "admin"
  keyfile: "/opt/spu/etc/ssh/users/admin/id_rsa"
  port: 8822
  command: "show diameter"
  command_memory: "show spu memory"
scrape_interval: 15s