name: Test and Build
on:
  - push
  - pull_request

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.14.1'
      - name: Tests
        run: |
          make build
#          make fmt
#          make vet
#          make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
#      - name: Build release type artifacts
#        run: make release
